# Generated by Django 4.2.13 on 2026-06-06 09:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('manager', '管理者'), ('executor', '执行者'), ('reviewer', '复核者')], max_length=20, verbose_name='角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='工位名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工位编号')),
                ('description', models.TextField(blank=True, verbose_name='工位描述')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('status', models.CharField(choices=[('pending_prep', '待准备'), ('in_progress', '进行中'), ('pending_review', '待复核'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_prep', max_length=20, verbose_name='状态')),
                ('scheduled_time', models.DateTimeField(verbose_name='计划时间')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.project', verbose_name='所属项目')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='复核者')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.station', verbose_name='工位')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('preparation_content', models.TextField(verbose_name='准备内容要求')),
                ('reception_content', models.TextField(verbose_name='接待内容要求')),
                ('closing_content', models.TextField(verbose_name='收尾内容要求')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '任务模板',
                'verbose_name_plural': '任务模板',
            },
        ),
        migrations.CreateModel(
            name='TaskFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending_prep', '待准备'), ('in_progress', '进行中'), ('pending_review', '待复核'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(choices=[('pending_prep', '待准备'), ('in_progress', '进行中'), ('pending_review', '待复核'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=20, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_records', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务流转记录',
                'verbose_name_plural': '任务流转记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.tasktemplate', verbose_name='任务模板'),
        ),
        migrations.CreateModel(
            name='ReceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='接待记录内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '接待记录',
                'verbose_name_plural': '接待记录',
            },
        ),
        migrations.CreateModel(
            name='PreparationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='准备记录内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '准备记录',
                'verbose_name_plural': '准备记录',
            },
        ),
        migrations.CreateModel(
            name='ExceptionHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handling_content', models.TextField(verbose_name='异常处理内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_handlings', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '异常处理',
                'verbose_name_plural': '异常处理',
            },
        ),
        migrations.CreateModel(
            name='ClosingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='收尾记录内容')),
                ('has_exception', models.BooleanField(default=False, verbose_name='是否有异常')),
                ('exception_description', models.TextField(blank=True, verbose_name='异常描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closing', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '收尾记录',
                'verbose_name_plural': '收尾记录',
            },
        ),
    ]
