# Generated by Django 4.2.13 on 2026-06-06 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending_prep', '待准备'), ('in_progress', '进行中'), ('pending_review', '待复核'), ('rectification_pending', '待整改'), ('rectified_pending_review', '已整改待复核'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_prep', max_length=30, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='taskflowrecord',
            name='new_status',
            field=models.CharField(choices=[('pending_prep', '待准备'), ('in_progress', '进行中'), ('pending_review', '待复核'), ('rectification_pending', '待整改'), ('rectified_pending_review', '已整改待复核'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=30, verbose_name='新状态'),
        ),
        migrations.AlterField(
            model_name='taskflowrecord',
            name='old_status',
            field=models.CharField(choices=[('pending_prep', '待准备'), ('in_progress', '进行中'), ('pending_review', '待复核'), ('rectification_pending', '待整改'), ('rectified_pending_review', '已整改待复核'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=30, verbose_name='原状态'),
        ),
        migrations.CreateModel(
            name='RectificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('preparation', '准备记录'), ('reception', '接待记录'), ('closing', '收尾记录')], max_length=20, verbose_name='整改环节')),
                ('rectification_content', models.TextField(verbose_name='整改意见')),
                ('rectification_note', models.TextField(blank=True, verbose_name='整改说明')),
                ('status', models.CharField(choices=[('pending', '待整改'), ('rectified', '已整改'), ('closed', '已闭环')], default='pending', max_length=20, verbose_name='整改状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rectified_at', models.DateTimeField(blank=True, null=True, verbose_name='整改时间')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectifications', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_rectifications', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectification_records', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '整改记录',
                'verbose_name_plural': '整改记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
