# Generated by Django 4.2.13 on 2026-06-06 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_status_alter_taskflowrecord_new_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(verbose_name='复盘结论')),
                ('problem_type', models.CharField(choices=[('process', '流程问题'), ('execution', '执行问题'), ('communication', '沟通问题'), ('resource', '资源问题'), ('quality', '质量问题'), ('other', '其他问题')], max_length=30, verbose_name='问题类型')),
                ('responsibility_stage', models.CharField(choices=[('preparation', '准备环节'), ('reception', '接待环节'), ('closing', '收尾环节'), ('review', '复核环节'), ('management', '管理环节'), ('other', '其他环节')], max_length=30, verbose_name='责任环节')),
                ('improvement_suggestion', models.TextField(verbose_name='改进建议')),
                ('followup_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('closed', '已闭环')], default='pending', max_length=30, verbose_name='跟进状态')),
                ('rectification_feedback', models.TextField(blank=True, verbose_name='整改反馈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rectification_feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='整改反馈时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务复盘记录',
                'verbose_name_plural': '任务复盘记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
