# Generated by Django 4.2.13 on 2026-06-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReviewOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建复盘'), ('update', '编辑复盘'), ('update_status', '更新跟进状态'), ('submit_feedback', '提交整改反馈'), ('delete', '删除复盘')], max_length=30, verbose_name='操作类型')),
                ('old_followup_status', models.CharField(blank=True, choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('closed', '已闭环')], max_length=30, null=True, verbose_name='原跟进状态')),
                ('new_followup_status', models.CharField(blank=True, choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('closed', '已闭环')], max_length=30, null=True, verbose_name='新跟进状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='core.taskreview', verbose_name='复盘记录')),
            ],
            options={
                'verbose_name': '复盘操作日志',
                'verbose_name_plural': '复盘操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
