# Generated by Django 4.2.13 on 2026-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taskreviewoperationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreview',
            name='followup_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='跟进截止时间'),
        ),
    ]
